# Generated by Django 3.0.5 on 2020-05-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('forum', '0002_auto_20200502_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadPage',
        ),
    ]
