# Generated by Django 3.0.5 on 2020-05-03 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('forum', '0004_forumpostpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumPostPage',
            new_name='ForumThreadPage',
        ),
    ]
